language: python

python:
  - "3.8"

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - pip install --upgrade pip
  - cd teUtils
  - pip install tellurium
  - pip install codecov
  - python setup.py install

script:
  - nosetests--with-coverage --cover-package=teUtils tests
